version: '3.8'

services:
  ripper:
    build:
      context: .
      tags:
        - s21toolkit/s21ripper:latest
    environment:
      BASE_URL: https://edu.21-school.ru/
      VIDEO_OUTPUT: /video # Optional
      VIDEO_W: 2560 # Optional
      VIDEO_H: 1440 # Optional
      HAR_OUTPUT: /log.har # Optional
      ROOTS_SEPARATOR: \n
      ROOTS: /app/roots
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro

      - ./roots:/app/roots:ro
      - ./outputs/video:/video:rw

      - type: bind
        source: $HOME/.s21.mjs
        target: /root/.s21.mjs
        read_only: true
        
      - type: bind
        source: ./outputs/log.har
        target: /log.har
